name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files in 'charts' dir
        id: changed-charts-files
        uses: tj-actions/changed-files@v46
        with:
          files: "charts/**"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        if: steps.changed-charts-files.outputs.any_changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
