name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-charts-files
        uses: tj-actions/changed-files@v46
        with:
          files: "charts/**"

      - name: List all modified files
        if: steps.changed-charts-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-charts-files.outputs.all_modified_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
